// A list of high-impact, bold Google Fonts suitable for the hero display.
// The format is `Family:wght@...` for variable fonts or just `Family` for standard.
export const googleFonts = [
	// Sans-serif & Display
	'Anybody',
	'Anton',
	'Archivo Black',
	'Bebas Neue',
	'Clash Display:wght@500',
	'DM Sans',
	'Figtree',
	'Inter',
	'Manrope',
	'Montserrat:wght@500;700',
	'Oswald',
	'Poppins:wght@500;700',
	'Raleway:wght@500;700',
	'Sora',
	'Space Grotesk',
	'Syne:wght@500;700',
	'Teko',
	'Unica One',
	'Work Sans',

	// Serif
	'Bodoni Moda:opsz@6..96',
	'Cormorant Garamond:wght@500;700',
	'Fraunces:opsz@9..144',
	'Libre Baskerville',
	'Lora',
	'Merriweather',
	'Playfair Display',
	'Prata',
	'PT Serif',
	'Quattrocento',
	'Source Serif Pro',
	'Zilla Slab',

	// Monospace
	'Sometype Mono',
	'Space Mono',
	'Major Mono Display',
  'Archivo:wght@900',
  'Rubik:wght@900',
  'Saira+Condensed:wght@800;900',
  'Exo+2:wght@800;900',
  'Barlow:wght@900',
  'Teko:wght@700',
  'Syncopate:wght@700',
  'Rajdhani:wght@700',
  'Kanit:wght@800;900',
  'Titillium+Web:wght@900',
  'Major+Mono+Display',
  'Unica+One',
  'Staatliches'
];
