// Dictionary of words starting with 'f'.
// Note: This is a starter set. You can add more or load from a service.
// The UI shows the word WITHOUT the leading 'f' because the leading 'f' is drawn separately.
export const fWords: string[] = [
  // English
  'fabric', 'fable', 'face', 'fact', 'factor', 'fall', 'family', 'fan', 'fancy', 'fantasy', 'farm', 'fashion', 'fast', 'fate', 'father', 'fault', 'fear', 'feast', 'feather', 'feature', 'feel', 'feeling', 'fiction', 'field', 'fight', 'figure', 'file', 'fill', 'film', 'final', 'finance', 'find', 'fine', 'finger', 'finish', 'fire', 'fish', 'fit', 'five', 'fix', 'flag', 'flame', 'flash', 'flat', 'flavor', 'flesh', 'flight', 'float', 'flood', 'floor', 'flow', 'flower', 'fly', 'focus', 'fog', 'fold', 'folk', 'follow', 'food', 'foot', 'force', 'forest', 'form', 'fortune', 'forward', 'foundation', 'four', 'fox', 'frame', 'framework', 'free', 'freedom', 'freeze', 'frequency', 'fresh', 'friend', 'front', 'fruit', 'fuel', 'full', 'fun', 'function', 'fund', 'future', 'fabricate', 'fabulous', 'facet', 'facilitate', 'facility', 'faction', 'failure', 'faint', 'fair', 'faith', 'falcon', 'fame', 'familiar', 'famine', 'famous', 'fanatic', 'fare', 'farewell', 'fascinate', 'fatal', 'fatigue', 'faucet', 'favorite', 'fearless', 'feasible', 'feat', 'federal', 'fee', 'feeble', 'feed', 'feedback', 'fellow', 'female', 'feminine', 'fence', 'ferry', 'fertile', 'festival', 'fetch', 'fever', 'few', 'fiancé', 'fiber', 'fickle', 'fierce', 'fiery', 'fifth', 'fifty', 'filter', 'filth', 'financial', 'finding', 'finite', 'fir', 'firm', 'first', 'fiscal', 'fitness', 'fixture', 'flair', 'flake', 'flank', 'flap', 'flare', 'flask', 'flatter', 'flaw', 'flee', 'fleece', 'fleet', 'flexible', 'flicker', 'flimsy', 'flinch', 'fling', 'flint', 'flip', 'flirt', 'flock', 'flop', 'floral', 'flour', 'flourish', 'flowery', 'fluent', 'fluid', 'fluffy', 'flurry', 'flush', 'flute', 'flutter', 'flux', 'foam', 'foe', 'foil', 'folder', 'fond', 'fool', 'forbid', 'forecast', 'forehead', 'foreign', 'foresee', 'forge', 'forget', 'forgive', 'fork', 'formal', 'format', 'former', 'formula', 'forsake', 'fort', 'forth', 'fortunate', 'forty', 'forum', 'fossil', 'foster', 'foul', 'found', 'fountain', 'fraction', 'fracture', 'fragile', 'fragment', 'fragrant', 'frail', 'frank', 'frantic', 'fraud', 'freak', 'freckle', 'freight', 'frenzy', 'frequent', 'friction', 'fright', 'fringe', 'frisky', 'frivolous', 'frog', 'frolic', 'frost', 'frown', 'frozen', 'frugal', 'frustrate', 'fry', 'fudge', 'fugitive', 'fulfill', 'fumble', 'fume', 'functional', 'funding', 'funeral', 'funny', 'fur', 'furious', 'furnace', 'furnish', 'furniture', 'further', 'fury', 'fuse', 'fusion', 'fuss', 'futile', 'fuzzy',

  // German
  'Fabel', 'Fabrik', 'Fach', 'Faden', 'Fähre', 'Fahne', 'Fahrt', 'Falke', 'Falle', 'Farbe', 'Farn', 'Fassade', 'Fass', 'fast', 'Faulheit', 'Faun', 'Faust', 'Favorit', 'Fax', 'Fazit', 'Feder', 'Fee', 'Fehler', 'Feier', 'fein', 'Feind', 'Feld', 'Felge', 'Fell', 'Fels', 'Fenster', 'Ferien', 'Ferne', 'Ferse', 'fest', 'Fest', 'fett', 'Feuer', 'Fiale', 'Fiasko', 'Fibel', 'Fichte', 'Fiktion', 'Filet', 'Film', 'Filter', 'Filz', 'Finanz', 'finden', 'Finger', 'Fink', 'Finne', 'Firma', 'Fisch', 'fix', 'flach', 'Flagge', 'Flamme', 'Flasche', 'Flaum', 'Fleck', 'Fledermaus', 'Fleisch', 'Flieder', 'Fliege', 'fliegen', 'Fliese', 'fließen', 'Flinte', 'Flirt', 'Flitter', 'Floh', 'Flocke', 'florieren', 'Flosse', 'Flöte', 'flott', 'Fluch', 'Flucht', 'Flug', 'Flügel', 'Fluss', 'Flut', 'Fokus', 'folgen', 'Folie', 'Folter', 'Fonds', 'Fontäne', 'fordern', 'Forelle', 'Form', 'Formel', 'forschen', 'Forst', 'fort', 'Forum', 'Fossil', 'Foto', 'Foyer', 'Fracht', 'Frage', 'Fragment', 'Fraktion', 'frank', 'Franse', 'Frau', 'frech', 'frei', 'Freude', 'Freund', 'Frieden', 'frisch', 'Frosch', 'Frost', 'früh', 'Fuchs', 'Fuge', 'fühlen', 'führen', 'Füller', 'Fund', 'Funk', 'Funke', 'für', 'Furt', 'Furz', 'Fusion', 'Fuß', 'Futter',

  // Spanish
  'fábrica', 'fácil', 'factor', 'facultad', 'falda', 'falso', 'falta', 'familia', 'famoso', 'fantasía', 'fantasma', 'farmacia', 'farol', 'fase', 'favor', 'fe', 'febrero', 'fecha', 'feliz', 'fenómeno', 'feria', 'feroz', 'ferrocarril', 'fiable', 'fibra', 'ficción', 'ficha', 'fidelidad', 'fiebre', 'fiesta', 'figura', 'fijar', 'fila', 'filial', 'filmar', 'filosofía', 'filtrar', 'fin', 'final', 'financiar', 'finca', 'fingir', 'fino', 'firma', 'fiscal', 'físico', 'flaco', 'flamenco', 'flecha', 'flexible', 'flor', 'flota', 'fluir', 'flujo', 'fobia', 'foco', 'fogata', 'folio', 'fondo', 'forma', 'formidable', 'fórmula', 'fortaleza', 'fortuna', 'forzar', 'foto', 'fracasar', 'fracción', 'frágil', 'francia', 'franja', 'frase', 'fraude', 'frecuencia', 'fregar', 'freír', 'frenar', 'freno', 'frente', 'fresa', 'fresco', 'frío', 'frito', 'frontera', 'fruta', 'fuego', 'fuente', 'fuera', 'fuerte', 'fuerza', 'fuga', 'fumar', 'función', 'fundación', 'fundamental', 'fundir', 'fúnebre', 'furioso', 'fútbol', 'futuro',

  // French
  'fable', 'fabricant', 'fabriquer', 'façade', 'face', 'facile', 'façon', 'facteur', 'facture', 'faculté', 'faible', 'faim', 'faire', 'faisan', 'fait', 'falloir', 'falsifier', 'famille', 'fan', 'fanfare', 'fantaisie', 'fantastique', 'fantôme', 'farce', 'farine', 'fasciner', 'fatigue', 'faute', 'fauteuil', 'fauve', 'faux', 'faveur', 'fébrile', 'féconder', 'fédéral', 'fée', 'féliciter', 'féminin', 'femme', 'fendre', 'fenêtre', 'fente', 'fer', 'ferme', 'fermer', 'féroce', 'fertile', 'fête', 'feu', 'feuille', 'feutre', 'février', 'fiable', 'fiancé', 'fibre', 'ficelle', 'fiche', 'fichier', 'fier', 'fierté', 'fièvre', 'figue', 'figure', 'fil', 'filet', 'fille', 'film', 'fils', 'filtre', 'fin', 'final', 'finance', 'finir', 'fiole', 'firme', 'fixer', 'flacon', 'flair', 'flamme', 'flanc', 'flanelle', 'flaque', 'flash', 'flatter', 'flèche', 'flegme', 'fleur', 'fleuve', 'flexible', 'flocon', 'flotter', 'fluide', 'flûte', 'foi', 'foie', 'foin', 'foire', 'fois', 'folie', 'fonction', 'fond', 'fondamental', 'fonder', 'fondre', 'fonds', 'fontaine', 'fonte', 'football', 'force', 'forêt', 'forfait', 'forge', 'forme', 'formel', 'formidable', 'formule', 'fort', 'forteresse', 'fortune', 'forum', 'fosse', 'fou', 'foudre', 'fouet', 'fougère', 'fouiller', 'foule', 'four', 'fourchette', 'fourmi', 'fournir', 'fourrure', 'foutaise', 'foyer', 'fraction', 'fracture', 'fragile', 'frais', 'fraise', 'franc', 'français', 'franchir', 'frange', 'frapper', 'fraude', 'frein', 'fréquent', 'frère', 'fresque', 'frigo', 'fripon', 'frire', 'frisson', 'froid', 'fromage', 'froment', 'front', 'frontière', 'frotter', 'fruit', 'fuir', 'fuite', 'fumée', 'funèbre', 'funérailles', 'furieux', 'fusée', 'fusil', 'fusion', 'futile', 'futur',

  // Italian
  'favola', 'fabbrica', 'faccia', 'facile', 'fatto', 'fattore', 'famiglia', 'famoso', 'fantasia', 'fantasma', 'farmacia', 'fascino', 'fase', 'fastidio', 'fato', 'favore', 'febbre', 'fede', 'fegato', 'felice', 'femmina', 'fenomeno', 'ferita', 'fermo', 'ferro', 'festa', 'fetta', 'feudo', 'fiaba', 'fiamma', 'fianco', 'fiato', 'fibra', 'fiducia', 'figlio', 'figura', 'fila', 'filo', 'filosofia', 'finale', 'finanza', 'finestra', 'fine', 'fino', 'fiore', 'firma', 'fisica', 'fiume', 'fiuto', 'flotta', 'fluido', 'fobia', 'focaccia', 'foce', 'foglia', 'folla', 'fondamento', 'fontana', 'forbici', 'foresta', 'forma', 'formaggio', 'formica', 'formula', 'forno', 'foro', 'forse', 'forte', 'fortuna', 'forza', 'foto', 'fragola', 'frana', 'frase', 'fratello', 'frazione', 'freddo', 'freno', 'frequenza', 'fretta', 'fronte', 'frutto', 'fucile', 'fuga', 'fulmine', 'fumo', 'funerale', 'fungo', 'fuoco', 'fuori', 'furbo', 'furia', 'fuso', 'futuro',

  // Portuguese
  'fábula', 'fábrica', 'faca', 'face', 'fácil', 'fado', 'faina', 'faixa', 'falar', 'falta', 'família', 'famoso', 'fantasia', 'fantasma', 'fardo', 'farinha', 'farmácia', 'farol', 'fatia', 'fato', 'favor', 'fé', 'febre', 'fechar', 'data', 'feliz', 'fêmea', 'fenômeno', 'ferida', 'férias', 'feroz', 'ferramenta', 'ferro', 'fertil', 'festa', 'festival', 'fevereiro', 'fezes', 'fiança', 'fibra', 'ficção', 'ficar', 'ficha', 'fiel', 'figo', 'figura', 'fila', 'filho', 'filme', 'filosofia', 'fim', 'final', 'finanças', 'fino', 'fio', 'firma', 'física', 'fivela', 'fixo', 'flauta', 'flecha', 'flor', 'floresta', 'flutuar', 'fluxo', 'fobia', 'foca', 'foco', 'fofoca', 'fogo', 'foguete', 'foice', 'folclore', 'folha', 'folia', 'fonte', 'fora', 'força', 'forma', 'formiga', 'fórmula', 'forno', 'forte', 'fortuna', 'fórum', 'foto', 'fôlego', 'fraco', 'frasco', 'frase', 'fraternidade', 'fraude', 'freio', 'frente', 'fresco', 'frio', 'fronteira', 'frota', 'fruta', 'fuga', 'fumaça', 'função', 'fundação', 'fundo', 'funeral', 'funil', 'fúria', 'futebol', 'futuro'
];


